import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../component/common/Navbar/Navbar";
//global
import "flowbite";
import "aos/dist/aos.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css"
          rel="stylesheet"
        />
          <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
          
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}

        <script src="https://demo.tailadmin.com/bundle.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/datepicker.min.js"></script>
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
      </body>
    </html>
  );
}
